### ISSUE TITLE
#9 patch causes errors with configuration files in UTF-8 format

### ISSUE THREAD

**Issue by kmcfate** [devstructure/blueprint#15]
Keep getting errors when it tries to dump the contents of a UTF-8 configuration file.

Reverting change in #9 makes errors go away.

Traceback (most recent call last):
  File "/usr/local/bin/blueprint-create", line 58, in <module>
    filename = getattr(b, options.generate)().dumpf()
  File "/usr/lib64/python2.7/site-packages/blueprint/sh.py", line 61, in dumpf
    f.write(out)
  File "/usr/lib64/python2.7/codecs.py", line 692, in write
    return self.writer.write(data)
  File "/usr/lib64/python2.7/codecs.py", line 352, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 9141: ordinal not in range(128)

**Comment by mrud** [comment]
Hm, strange can you please provide a sample file? I created files with umlautes and everything worked for me.

**Comment by rcrowley** [comment]
I'm having trouble reproducing this particular stack trace.  This is happening because the byte `0xC2` is not on its own is not valid UTF-8.  `0xC2` is LATIN CAPITAL LETTER A WITH CIRCUMFLEX in Latin-1.

Invalid UTF-8 bytes result in base-64-encoded file content in a blueprint, which is propagated to generated shell code without decoding so it is unclear to me where this byte appears unless it's in a pathname.

Could you provide more details, please?

**Comment by rcrowley** [comment]
I've stumbled upon a reproducible case.  I'll post again as soon as I have the problem isolated.

**Comment by rcrowley** [comment]
e910b5cacd2492a476ecb0d9801db98218be0cd1 that claims to close #3 is lying.  It closes this bug.
